version: '3'
services:

  # fast-api-example
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: devco/fast-api-example
    container_name: devco
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8000"
    environment:
      SERVICE_NAME: app
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - app-network
  # db
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      SERVICE_NAME: db
      POSTGRES_PASSWORD: example
    networks:
      - app-network

#Redes
networks:
  app-network:
    driver: bridge
